ANSWERS/django2.0/music/bands/urls.py
"""
URL Configuration for bands
"""
from django.conf.urls import url
from . import views   # import views from app
from . import classviews

urlpatterns = [
    # add url patterns for the bands app here

    # Example:
    url(r'^$', views.home, name='home'),
    url(r'^sorted$', views.bands_sorted, name='bandssorted'),
    url(r'^list$', views.bands_list, name='bandslist'),
    url(r'^classlist$', classviews.BandListView.as_view(), name='bandsclasslist'),
    url(r'^class/(?P<pk>\d+)$', classviews.BandDetailView.as_view(), name='bandclassdetails'),
    url(r'^listmore$', views.bands_list_more, name='bandslistmore'),
    url(r'^genre/(?P<genre_name>[\w\s]+)$', views.bands_by_genre, name='bandsbygenre'),
    url(r'^search/(?P<search_term>[\w\s]+)$', views.bands_search, name='bandssearch'),
    url(r'^(?P<id>\d+)$', views.band_details, name='banddetails'),
    url(r'^(?P<band_name>[\w\s]+)$', views.band_basic, name='bandbasic'),
]

ANSWERS/django2.0/music/music/urls.py
"""music URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  url(r'^$', views.home, name='home')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  url(r'^$', Home.as_view(), name='home')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls', namespace="blog"))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

# site-wide route mapping
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # example
    url(r'^bands/', include('bands.urls', namespace="bands")),
]

# include Django Debug toolbar if DEBUG is set
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ANSWERS/django2.0/music/bands/models.py
from django.db import models
# these are the plain models that don't have the
# extra code from chapter 9

class Genre(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Member(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Band(models.Model):
    name = models.CharField(max_length=32)
    genre = models.ForeignKey(Genre)
    members = models.ManyToManyField(Member)

    def __str__(self):
        return self.name

ANSWERS/django2.0/music/bands/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Band, Genre


def home(request):
    return HttpResponse("Welcome to the Bands app")


def band_basic(request, band_name):
    band = Band.objects.get(name=band_name)
    data = {'band': band}
    return render(request, 'band_basic.html', data)


def bands_list(request):
    bands = Band.objects.all()
    data = {'bands': bands, 'title': 'Bands'}
    return render(request, 'bands_list.html', data)

def bands_sorted(request):
    bands = Band.objects.all().order_by('name')
    data = {'bands': bands, 'title': 'Bands'}
    return render(request, 'bands_list.html', data)

def band_details(request, id):
    band = Band.objects.get(id=id)
    data = {'band': band}
    return render(request, 'band_details.html', data)


def bands_by_genre(request, genre_name):
    genre = get_object_or_404(Genre, name=genre_name)
    bands = Band.objects.filter(genre=genre)
    data = {'genre': genre, 'bands': bands, 'title': 'Bands'}
    return render(request, 'bands_list.html', data)


def bands_search(request, search_term):
    bands = Band.objects.all().filter(name__icontains=search_term)
    data = {'bands': bands, 'title': 'Bands'}
    return render(request, 'bands_list.html', data)

# chapter 9
def bands_list_more(request):
    bands = Band.objects.all()
    data = {'bands': bands, 'title': 'Bands'}
    return render(request, 'bands_list_more.html', data)

ANSWERS/django2.0/music/bands/templates/band_basic.html
{% extends "bands_base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        Band: {{ band.name }}
    </div>
    <div class="row">
        Genre: {{ band.genre }}
    </div>
</div>
{% endblock content %}

ANSWERS/django2.0/music/bands/templates/band_class_details.html
{% extends "bands_base.html" %}

{% block content %}

<h1>{{ band.name }}</h1>
<h2>Genre: {{ band.genre }}</h2>
<h2>Members:</h2>
<ul>
{% for member in band.members.all %}
<li>{{ member.name }}</li>
{% endfor %}
</ul>

<a href="{% url 'bands:bandsclasslist' %}">Return to band list</a>
{% endblock %}

ANSWERS/django2.0/music/bands/templates/band_details.html
{% extends "bands_base.html" %}

{% block content %}

<h1>{{ band.name }}</h1>
<h2>Genre: {{ band.genre }}</h2>
<h2>Members:</h2>
<ul>
{% for member in band.members.all %}
<li>{{ member.name }}</li>
{% endfor %}
</ul>

<a href="{% url 'bands:bandslist' %}">Return to band list</a>
{% endblock %}

ANSWERS/django2.0/music/bands/templates/bands_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}bands{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    {% endblock css %}

  </head>

  <body>

    <div class="container">

      {% block header %}{% endblock header %}
      {% block content %}
        <p>Default content for bands</p>
      {% endblock content %}
      {% block footer %}{% endblock footer %}

    </div> <!-- /container -->

    <!-- Javascript Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Third-party javascript libraries go here -->

      <!-- App-specific Javascript in this file -->


   {#   <script src="{% static 'js/bands.js'"></script> #}


    {% endblock javascript %}

  </body>
</html>

ANSWERS/django2.0/music/bands/templates/bands_class_list.html
{% extends "bands_base.html" %}

{% block title %}

    {% if genre %}
        {{ genre.name }}
    {% endif %}

    {{ title }}

{% endblock title %}

{% block content %}

<h1>Pick a Band:</h1>

{% for band in bands %}
<div class="row">
    <div class="col-3">
    <a href="{% url 'bands:bandclassdetails' band.id  %}">{{ band.name }}</a>
    </div>
    <div class="col-3">
    {{ band.genre }}
    </div>
</div>
{% endfor %}

{% endblock %}

</body>
</html>

ANSWERS/django2.0/music/bands/templates/bands_list.html
{% extends "bands_base.html" %}

{% block title %}

    {% if genre %}
        {{ genre.name }}
    {% endif %}

    {{ title }}

{% endblock title %}

{% block content %}

<h1>Pick a Band:</h1>

{% for band in bands %}
<div class="row">
    <div class="col-3">
    <a href="{% url 'bands:banddetails' band.id  %}">{{ band.name }}</a>
    </div>
    <div class="col-3">
    {{ band.genre }}
    </div>
</div>
{% endfor %}

{% endblock %}

</body>
</html>

ANSWERS/django2.0/music/bands/templates/bands_list_more.html
{% extends "bands_base.html" %}

{% block title %}

    {% if genre %}
        {{ genre.name }}
    {% endif %}

    {{ title }}

{% endblock title %}

{% block content %}

<h1>Pick a Band:</h1>

{% for band in bands %}
<div class="row">
    <div class="col-3">
    <a href="{% url 'bands:banddetails' band.id  %}">{{ band.name }}</a>
    </div>
    <div class="col-3">
    {{ band.get_genre }}
    </div>
</div>
{% endfor %}

{% endblock %}

</body>
</html>

ANSWERS/django2.0/music/bands/templates/sample.html
{% extends "bands_base.html" %}
{% block content %}
<div class="container">
Sample content for bands
</div>
{% endblock content %}