EXAMPLES/django2.0/djrest/apiv1/urls.py
"""
URL Configuration for apiv1
"""
from django.conf.urls import url
from . import views   # import views from app
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Superhero API')

urlpatterns = [
    # add url patterns for the apiv1 app here

    # Example:
    url(r'^$', schema_view, name='schema'),
    url(r'^heros/(?P<pk>\d+)', views.superhero_detail, name='superherodetail'),
    url(r'^heros$', views.superhero_list, name='herolist'),
    url(r'^enemylist', views.EnemyList.as_view(), name='enemylist'),
    url(r'^enemy/(?P<pk>\d+)', views.EnemyDetail.as_view(), name='enemydetail'),
    url(r'^powers/(?P<pk>\d+)', views.power, name="power"),
    url(r'^powers', views.power_list, name='powerlist'),
]

EXAMPLES/django2.0/djrest/djrest/djrest/urls.py
"""djrest URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  url(r'^$', views.home, name='home')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  url(r'^$', Home.as_view(), name='home')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls', namespace="blog"))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

# site-wide route mapping
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # example
    url(r'^superheroes/', include('superheroes.urls', namespace="superheroes")),
    url(r'^api/v1/', include('apiv1.urls', namespace="apiv1")),
    url(r'^restjs/', include('restjs.urls', namespace="restjs")),
]

# include Django Debug toolbar if DEBUG is set
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

EXAMPLES/django2.0/djrest/djrest/urls.py
"""djrest URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  url(r'^$', views.home, name='home')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  url(r'^$', Home.as_view(), name='home')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls', namespace="blog"))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django import VERSION

# site-wide route mapping
if VERSION[0] >= 2:
    urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^superheroes/', include(('superheroes.urls', "superheroes"))),
        url(r'^api/v1//', include(('apiv1.urls', "apiv1"))),
        url(r'^restjs/', include(('restjs.urls', "restjs"))),
    ]
else:
    urlpatterns = [
        url(r'^admin/', admin.site.urls),
        # example
        url(r'^superheroes/', include('superheroes.urls', namespace="superheroes")),
        url(r'^api/v1/', include('apiv1.urls', namespace="apiv1")),
        url(r'^restjs/', include('restjs.urls', namespace="restjs")),
    ]

# include Django Debug toolbar if DEBUG is set
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

EXAMPLES/django2.0/djrest/superheroes/urls.py
"""
URL Configuration for superheroes
"""
from django.conf.urls import url
from . import views   # import views from app
from . import views404
from . import viewsbasictemplate
from . import viewstemplate
from . import viewsqueries
from . import viewsextra

from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Pastebin API')

urlpatterns = [
]



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^hero/(?P<hero_name>.*)/(?P<hero_city>.*)', views.hero, name="hero"),
    url(r'^hero2/(.*)/$', views.hero2, name="hero2"),
    url(r'^heroerror$', views.heroerror, name="heroerror"),
    url(r'^hero404x/(?P<hero_name>.*)', views404.hero404, name="hero404"),
    url(r'^hero404sc/(?P<hero_name>.*)', views404.hero404sc, name="hero404sc"),
    url(
        r'^herotemplate101/(?P<hero_name>.*)',
        viewsbasictemplate.hero_basic_template,
        name="herobasictemplate",
    ),
    url(
        r'^herohardway/(?P<hero_name>.*)',
        viewstemplate.hero_hard_way,
        name="herohardway",
    ),
    url(
        r'^heroeasyway/(?P<hero_name>.*)',
        viewstemplate.hero_easy_way,
        name="heroeasyway",
    ),
    url(
        r'^herolookups/(?P<hero_name>.*)',
        viewstemplate.hero_lookups,
        name="herolookups",
    ),
    url(
        r'^herofilters/(?P<hero_name>.*)',
        viewstemplate.hero_filters,
        name="herofilters",
    ),
    url(
        r'^herotags/(?P<hero_name>.*)',
        viewstemplate.hero_tags,
        name="herotags",
    ),
    url(
        r'^herodetails/(?P<hero_name>.*)',
        viewstemplate.hero_details,
        name="herodetails",
    ),
    url(
        r'^(?i)heroescape/(?P<hero_name>.*)',
        viewstemplate.hero_escape,
        name="heroescape",
    ),
    url(
        r'^herourls',
        viewstemplate.hero_urls,
        name="herourls",
    ),
    url(
        r'^herostatic/(?P<hero_name>.*)',
        viewstemplate.hero_static,
        name="herostatic",
    ),
    url(
        r'^heroqueries',
        viewsqueries.hero_queries,
        name="heroqueries",
    ),
    url(
        r'^heroextra',
        viewsextra.hero_extra,
        name='heroextra',
    ),
]

EXAMPLES/django2.0/djrest/djrest/superheroes/models.py
from django.db import models
from datetime import date

class Power(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class DefaultDate(models.DateField):
    # predefined name "from_db_value"
    def from_db_value(self, value, expression, connection, context):
        if value is None:
            value = date.today()
        return value

class City(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

class Enemy(models.Model):
    name = models.CharField(max_length=32, unique=True)
    powers = models.ManyToManyField(Power)

    class Meta:
        permissions = [('create_dataframe', 'Can Create Dataframe')]

    def __str__(self):
        return self.name

class Superhero(models.Model):
    name = models.CharField(max_length=32, unique=True)
    real_name = models.CharField(max_length=32)
    date_of_death = DefaultDate(null=True)
    secret_identity = models.CharField(max_length=32)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    powers = models.ManyToManyField(Power)
    enemies = models.ManyToManyField(Enemy)

    def __str__(self):
        return self.name

EXAMPLES/django2.0/djrest/superheroes/models.py
from django.db import models
from datetime import date

class Power(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class DefaultDate(models.DateField):
    # predefined name "from_db_value"
    def from_db_value(self, value, expression, connection, context):
        if value is None:
            value = date.today()
        return value

class City(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

class Enemy(models.Model):
    name = models.CharField(max_length=32, unique=True)
    powers = models.ManyToManyField(Power)

    class Meta:
        permissions = [('create_dataframe', 'Can Create Dataframe')]

    def __str__(self):
        return self.name

class Superhero(models.Model):
    name = models.CharField(max_length=32, unique=True)
    real_name = models.CharField(max_length=32)
    date_of_death = DefaultDate(null=True)
    secret_identity = models.CharField(max_length=32)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    powers = models.ManyToManyField(Power)
    enemies = models.ManyToManyField(Enemy)

    def __str__(self):
        return self.name

EXAMPLES/django2.0/djrest/djrest/superheroes/views.py
from django.http import HttpResponse, Http404
from .models import Superhero

def home(request):
    return HttpResponse("Welcome to my app")

def hero(request, hero_city='Petaluma', hero_name=""):
    if hero_city == '':
        hero_city = 'Corning, NY'
    print("hero_city:", hero_city, repr(hero_city), type(hero_city))
    # if hero_city is None:
    #     print('wahhhhh')
    s = Superhero.objects.get(name=hero_name)
    return HttpResponse(
        "{} is really {} from {}".format(s.secret_identity, s.name, hero_city)
    )

def hero2(request, hero_name):
    return HttpResponse(
        "I'm {}!".format(hero_name)
    )

def heroerror(request):
    raise Http404("Oops")

EXAMPLES/django2.0/djrest/superheroes/views.py
from django.http import HttpResponse, Http404
from .models import Superhero

def home(request):
    return HttpResponse("Welcome to my app")

def hero(request, hero_city='Petaluma', hero_name=""):
    if hero_city == '':
        hero_city = 'Corning, NY'
    print("hero_city:", hero_city, repr(hero_city), type(hero_city))
    # if hero_city is None:
    #     print('wahhhhh')
    s = Superhero.objects.get(name=hero_name)
    return HttpResponse(
        "{} is really {} from {}".format(s.secret_identity, s.name, hero_city)
    )

def hero2(request, hero_name):
    return HttpResponse(
        "I'm {}!".format(hero_name)
    )

def heroerror(request):
    raise Http404("Oops")

EXAMPLES/django2.0/djrest/superheroes/templates/hero_basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hero_name }}</title>
</head>
<body>
{% spam = 'pig meat' %}
<h1>{{ hero_name }}</h1>
<h2>Secret Identity: {{ secret_identity }}</h2>
<h2>Real Name: {{ real_name }} {{ spam }}</h2>
</body>
</html>

{# this is a comment #}

{#

{%  tag %}

{{ variable | filter | filter ... }}

#}

EXAMPLES/django2.0/djrest/superheroes/templates/hero_details.html
{% extends "superheroes_base.html" %}

{% block content %}

<h1>{{ hero.name }}</h1>
<h2>Secret Identity: {{ hero.secret_identity }}</h2>
<h2>Real Name: {{ hero.real_name }}</h2>
<h3>Powers: {{ hero.powers.all | join:", "}}</h3>
<h3>Enemies: {{ hero.enemies.all | join:", " }}</h3>

<a href="{% url 'superheroes:herourls' %}">Return to hero list</a>

{% block.super %}

{% endblock content %}


{% block title %}THIS IS OUT OF ORDER!{% endblock title %}

EXAMPLES/django2.0/djrest/superheroes/templates/hero_escape.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hero.name }}</title>
    <style>.blue { color: blue; } .red { color: red; }</style>
</head>
<body>
<h1>{{ hero.name }}</h1>

<h2>Secret Identity: {{ hero.secret_identity }}</h2>

<h3>Not safe: {{ html_fragment }}</h3>
<h3>Safe: {{ html_fragment | safe }}</h3>


</body>
</html>

EXAMPLES/django2.0/djrest/superheroes/templates/hero_extra.html
{% extends "superheroes_base.html" %}

{% block content %}
<h2>Enemy Counts</h2>
{% for hero in heroes %}
<h4>{{ hero.name }} {{ hero.num_enemies }}</h4>
{% endfor %}
<hr/>
<h2>{{ fliers.num_fliers }} superheroes can fly</h2>
{% endblock content %}

EXAMPLES/django2.0/djrest/superheroes/templates/hero_filters.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hero.name }}</title>
</head>
<body>
<h1>{{ hero.name }}</h1>
<h2>Secret Identity: {{ hero.secret_identity | upper }}</h2>
<h2>Secret Identity (short):
    {{ hero.secret_identity | slice:"0:5" }}
</h2>
{% comment %}
<h2>Real Name: {{ hero.real_name | upper }}</h2>
<h2>First enemy: {{ hero.enemies.all.0 }}</h2>
<h3>Raw enemies list: {{ hero.enemies.all }}</h3>
<h3>Number of enemies: {{ hero.enemies.all | length }}</h3>
<h3>Enemies: {{ hero.enemies.all | join:", " }}</h3>
<h3>Enemies: <br/>{{ hero.enemies.all | join:"<br/>" }}</h3>
{% endcomment %}

</body>
</html>

EXAMPLES/django2.0/djrest/superheroes/templates/hero_lookups.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hero.name }}</title>
</head>
<body>
{% with spam="fatty pig meat" ham="pig leg" %}
<h1>{{ hero.name }}</h1>
<h2>Secret Identity: {{ hero.secret_identity }}</h2>
<h2>Real Name: {{ hero.real_name }}</h2>
<h2>First enemy: {{ hero.enemies.all.0 }}</h2>
<h3>Enemies list: {{ hero.enemies.all.1.powers.all.0 }}</h3>
{% endwith %}
</body>
</html>

EXAMPLES/django2.0/djrest/superheroes/templates/hero_queries.html
{% extends "superheroes_base.html" %}

{% block content %}
<h1>{{ page_title }}</h1>

<dl>
{% for query, result in query_pairs %}
    <dt>{{ query }}</dt>
    <dd>{{ result }}</dd>
    <br/>
{% endfor %}
</dl>

{% endblock %}

EXAMPLES/django2.0/djrest/superheroes/templates/hero_static.html
{% extends "superheroes_base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col"><h1>{{ hero.name }}</h1></div>
    </div>
    <div class="row">
        <div class="col-3">Secret Identity</div>
        <div class="col">&ldquo;{{ hero.secret_identity }}&rdquo;</div>
    </div>
    <div class="row">
        <div class="col-3">Real Name</div>
        <div class="col">{{ hero.real_name }}</div>

    </div>
    <div class="row">
        <div class="col-3">Powers</div>
        <div class="col">{{ hero.powers.all | join:", " }}</div>
    </div>
    <div class="row">
        <div class="col-3">Enemies</div>
        <div class="col">{{ hero.enemies.all | join:", " }}</div>
    </div>

    <img
        src="{% get_static_prefix %}{{ image_name }}.jpg"
        alt="My image"
        width="400"
    />

</div>

{% endblock %}

EXAMPLES/django2.0/djrest/superheroes/templates/hero_tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hero.name }}</title>
    <style>.blue { color: blue; } .red { color: red; }</style>
</head>
<body>
<h1>{{ hero.name }}</h1>

<h2>Secret Identity: {{ hero.secret_identity }}</h2>

<h2>Real Name:

{% if hero.real_name|length > 8 %}
    <span class="red">{{ hero.real_name }}</span>
{% else %}
    <span class="blue">{{ hero.real_name }}</span>
{% endif %}

</h2>

<h2>Enemies:</h2>
<ul>
{% for enemy in hero.enemies.all %}
    <h3><li>{{ enemy }}</li></h3>
{% endfor %}
</ul>
</body>
</html>

{% comment "just some notes" %}
This is some random text that
should not show up
in the page
{% endcomment %}

EXAMPLES/django2.0/djrest/superheroes/templates/hero_urls.html
{% extends "superheroes_base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<h1>Pick a hero (URL version):</h1>

{% for hero in superheroes %}
<h3>
    <a href="{% url 'superheroes:herodetails' hero.name  %}">{{ hero.name }}</a>
</h3>
{% endfor %}

{% endblock %}

</body>
</html>

EXAMPLES/django2.0/djrest/superheroes/templates/not_a_404.html
{% extends "superheroes_base.html" %}
{% block content %}
<div class="container">
Uh-oh
</div>
{% endblock content %}

EXAMPLES/django2.0/djrest/superheroes/templates/sample.html
{% extends "superheroes_base.html" %}
{% block content %}
<div class="container">
Sample content for superheroes
</div>
{% endblock content %}

EXAMPLES/django2.0/djrest/superheroes/templates/superheroes_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}superheroes{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    {% endblock css %}

  </head>

  <body>

    <div class="container">

      {% block header %}{% endblock header %}
      {% block content %}
        <p>Default content for superheroes</p>
      {% endblock content %}
      {% block footer %}{% endblock footer %}

    </div> <!-- /container -->

    <!-- Javascript Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Third-party javascript libraries go here -->

      <!-- App-specific Javascript in this file -->

      <script src="{% static 'js/superheroes.js' %}"></script>


    {% endblock javascript %}

  </body>
</html>